/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			keyframes: {
				"fade-dot": {
					"0%, 100%": { opacity: "0.2" },
					"50%": { opacity: "1" },
				},
			},
			animation: {
				"fade-dot": "fade-dot 1.4s ease-in-out infinite",
			},
		},
		colors: {
			transparent: "transparent",
			current: "currentColor",
			white: "#ffffff",
			black: "#000000",
			// Standard Tailwind colors for prototype UI patterns
			gray: {
				50: "#f9fafb",
				100: "#f3f4f6",
				200: "#e5e7eb",
				300: "#d1d5db",
				400: "#9ca3af",
				500: "#6b7280",
				600: "#4b5563",
				700: "#374151",
				800: "#1f2937",
				900: "#111827",
			},
			blue: {
				50: "#eff6ff",
				100: "#dbeafe",
				200: "#bfdbfe",
				400: "#60a5fa",
				500: "#3b82f6",
				600: "#2563eb",
				700: "#1d4ed8",
			},
			green: {
				50: "#f0fdf4",
				100: "#dcfce7",
				500: "#22c55e",
				600: "#16a34a",
				700: "#15803d",
			},
			red: {
				50: "#fef2f2",
				200: "#fecaca",
				500: "#ef4444",
				600: "#dc2626",
				700: "#b91c1c",
			},
			amber: {
				500: "#f59e0b",
			},
			cyan: {
				500: "#06b6d4",
			},
			// VSCode CSS variable mappings
			vsc: {
				foreground: "var(--vscode-foreground)",
				"editor-foreground": "var(--vscode-editor-foreground)",
				"editor-background": "var(--vscode-editor-background)",
				focusBorder: "var(--vscode-focusBorder)",
				errorForeground: "var(--vscode-errorForeground)",
				descriptionForeground: "var(--vscode-descriptionForeground)",
				"icon-foreground": "var(--vscode-icon-foreground)",
				"button-background": "var(--vscode-button-background)",
				"button-foreground": "var(--vscode-button-foreground)",
				"button-hoverBackground": "var(--vscode-button-hoverBackground)",
				"button-secondaryForeground": "var(--vscode-button-secondaryForeground)",
				"button-secondaryBackground": "var(--vscode-button-secondaryBackground)",
				"button-secondaryHoverBackground": "var(--vscode-button-secondaryHoverBackground)",
				"input-background": "var(--vscode-input-background)",
				"input-border": "var(--vscode-input-border)",
				"input-foreground": "var(--vscode-input-foreground)",
				"input-placeholderForeground": "var(--vscode-input-placeholderForeground)",
				"dropdown-background": "var(--vscode-dropdown-background)",
				"dropdown-border": "var(--vscode-dropdown-border)",
				"dropdown-foreground": "var(--vscode-dropdown-foreground)",
				"sideBar-background": "var(--vscode-sideBar-background)",
				"sideBar-foreground": "var(--vscode-sideBar-foreground)",
				"sideBarTitle-foreground": "var(--vscode-sideBarTitle-foreground)",
				"panel-background": "var(--vscode-panel-background)",
				"panel-border": "var(--vscode-panel-border)",
				"badge-background": "var(--vscode-badge-background)",
				"badge-foreground": "var(--vscode-badge-foreground)",
				"list-activeSelectionBackground": "var(--vscode-list-activeSelectionBackground)",
				"list-activeSelectionForeground": "var(--vscode-list-activeSelectionForeground)",
				"list-hoverBackground": "var(--vscode-list-hoverBackground)",
				"list-hoverForeground": "var(--vscode-list-hoverForeground)",
				"editorWidget-background": "var(--vscode-editorWidget-background)",
				"editorWidget-foreground": "var(--vscode-editorWidget-foreground)",
				"editorWidget-border": "var(--vscode-editorWidget-border)",
				"textLink-foreground": "var(--vscode-textLink-foreground)",
				"textLink-activeForeground": "var(--vscode-textLink-activeForeground)",
				"terminal-ansiGreen": "var(--vscode-terminal-ansiGreen)",
				"terminal-ansiRed": "var(--vscode-terminal-ansiRed)",
				"terminal-ansiCyan": "var(--vscode-terminal-ansiCyan)",
				"terminal-ansiYellow": "var(--vscode-terminal-ansiYellow)",
				"widget-shadow": "var(--vscode-widget-shadow)",
				"scrollbarSlider-background": "var(--vscode-scrollbarSlider-background)",
				"scrollbarSlider-hoverBackground": "var(--vscode-scrollbarSlider-hoverBackground)",
				"scrollbarSlider-activeBackground": "var(--vscode-scrollbarSlider-activeBackground)",
			},
		},
	},
	plugins: [],
	corePlugins: {
		// Disable Preflight (Tailwind's CSS reset) to avoid breaking existing
		// Emotion-styled components in Design View, Data Mapper, etc.
		preflight: false,
	},
};
