packages:
  - 'workspaces/mi/*'
  - 'workspaces/mi/shared-syntax-tree'
  - 'workspaces/mi/wso2-platform-core'
  - 'submodules/vscode-extensions/workspaces/common-libs/font-wso2-vscode'
  - 'submodules/vscode-extensions/workspaces/common-libs/ui-toolkit'
  - 'submodules/vscode-extensions/workspaces/common-libs/service-designer'
  - 'submodules/vscode-extensions/workspaces/common-libs/playwright-vscode-tester'
