packages:
  - 'workspaces/api-designer/*'
  - 'workspaces/api-tryit/*'
  - 'workspaces/apk/*'
  - 'workspaces/*'
  - 'workspaces/ballerina/*'
  - 'workspaces/choreo/*'
  - 'workspaces/wso2-platform/*'
  - 'workspaces/api-tryit/*'
  - "workspaces/bi/*"
  - 'workspaces/common-libs/*'
  - 'workspaces/mi/*'
  - 'workspaces/mcp-inspector/*'
  - 'workspaces/hurl-client/*'
