name: Daily Build
on:
  schedule:
    - cron:  '30 13 * * *'

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    secrets: inherit  
    with:
      mi: true
      runTests: true
      runMIE2ETests: true
      continueOnTrivyFailure: true

  NotifyEditorSuccess:
    name: Notify Editor Team
    needs: Build
    if: ${{ needs.Build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Restore build
        uses: actions/download-artifact@v4
        with:
          name: ExtBuild
          path: ./

      - name: Set up workspace
        run: |
          unzip build.zip
          rm build.zip

      - name: Notification - Editor Team
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: "WSO2 Integrator: MI"
          fileName: micro-integrator
          chatAPI: ${{ secrets.EDITOR_TEAM_CHAT_API }}

  NotifyMISuccess:
    name: Notify MI Team
    needs: Build
    if: ${{ needs.Build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Restore build
        uses: actions/download-artifact@v4
        with:
          name: ExtBuild
          path: ./

      - name: Set up workspace
        run: |
          unzip build.zip
          rm build.zip

      - name: Notification - MI
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: "WSO2 Integrator: MI"
          fileName: micro-integrator
          chatAPI: ${{ secrets.MI_TEAM_CHAT_API }}

  NotifyEditorFailure:
    needs: Build
    if: ${{ always() && needs.Build.result != 'success' && github.repository == 'wso2/mi-vscode'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Failure Notification"
        uses: ./.github/actions/failure-notification
        with:
          title: "Daily Build Failed"
          run_id: ${{ github.run_id }}
          chat_api: ${{ secrets.EDITOR_TEAM_CHAT_API }}
          repository: ${{ github.repository }}
